### ISSUE TITLE
Monter and Health UI

### ISSUE THREAD

**Issue by RJDulac** [RJDulac/Open-Source-Interactive-RPG#1]
Health for monsters and players need a UI component.

**Comment by sambatlim** [comment]
Is this count in Hacktoberfest?

**Comment by sambatlim** [comment]
If it count in Hacktoberfest, could you assign this for me?
I need two more pull requests.

**Comment by tsturtz** [comment]
Oops sorry to jump ahead of you @sambatlim. I should have commented first. I just wrapped up a PR for this.

**Comment by tsturtz** [comment]
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

@RJDulac - if you don't mind following the hacktoberfest guide to make this PR count 😄 ☝️

**Comment by RJDulac** [comment]
I'm trying to figure out how to set this up for hacktoberfest. I'm very sorry I thought I just had to add a label.

**Comment by RJDulac** [comment]
> > Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
> 
> @RJDulac - if you don't mind following the hacktoberfest guide to make this PR count 😄 ☝️

Did it count now that I've added "hacktoberfest" to the topic section?

**Comment by tsturtz** [comment]
Yes that did it thanks! Have fun with your project!

**Comment by RJDulac** [comment]
Awesome! Thanks!
