### ISSUE TITLE
Set Win Condition

### ISSUE THREAD

**Issue by RJDulac** [RJDulac/Open-Source-Interactive-RPG#10]
Set a win condition for who wins. Check if the health is 0 or less from both the monster and player to determine who wins. Show a modal of who wins. If any state is used, implement it with redux.

**Comment by lakshyaTaragi** [comment]
@RJDulac I would like to work on this.

**Comment by RJDulac** [comment]
Go for it!

**Comment by lakshyaTaragi** [comment]
I have created a pull request for the same.

**Comment by RJDulac** [comment]
Thanks for your contribution!
